// Generated by scripts/bake-stickers.mjs — run `pnpm stickers` to update.
// Do not edit by hand.

/** Stickers with baked die-cut artwork under static/stickers/. */
export const BAKED_STICKERS: ReadonlySet<string> = new Set([
	'star',
	'heart',
	'sparkles',
	'fire',
	'cat',
	'rocket',
	'sushi',
	'dice',
	'crown',
	'dragon',
	'ufo',
	'rainbow'
]);

/**
 * How much bigger than the sticker box a baked asset is drawn. The artwork
 * occupies 61.3% of its canvas — the rest is room for the rim and shadows —
 * so the image overflows its box by this much to land the artwork itself at
 * 86%, the size the unbaked path draws it at. The foil mask shares the
 * canvas, so it is drawn at this scale too and registers exactly.
 */
export const BAKED_ART_SCALE = 1.4041;
